/**
 * NAS GDP -- wrapper around existing PDF-based extraction
 * Reuses: scripts/extract_nas_pdf.py + scripts/build-nas-gdp-artifact.cjs
 * This script simply runs the existing pipeline and verifies output.
 */

const path = require("path");
const fs = require("fs");

const PROJECT_ROOT = path.resolve(__dirname, "../..");
const PDF_PATH = path.join(PROJECT_ROOT, "data/raw/mospi/STATE_SDP/nsdp_2025_09_01.pdf");
const BUILD_SCRIPT = path.join(PROJECT_ROOT, "scripts/build-nas-gdp-artifact.cjs");

function main() {
  console.log("[NAS_GDP] Checking PDF source...");
  if (!fs.existsSync(PDF_PATH)) {
    console.error(`  PDF not found: ${PDF_PATH}`);
    console.error("  Skipping NAS_GDP -- source unavailable");
    return { source_status: "source_unavailable", observations: [] };
  }

  console.log(`  PDF found: ${PDF_PATH}`);

  // Verify the existing artifact (generated by build-nas-gdp-artifact.cjs)
  const artifactPath = path.join(PROJECT_ROOT, "public/data/mospi/nas-gdp-mvp.json");
  if (!fs.existsSync(artifactPath)) {
    console.error(`  Artifact not found: ${artifactPath}`);
    console.error("  Skipping NAS_GDP -- artifact missing");
    return { source_status: "source_unavailable", observations: [] };
  }

  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));
  const obsCount = artifact.observations?.length || 0;
  console.log(`  Artifact found: ${obsCount} observations`);

  // Update catalog
  const { updateCatalog } = require("./lib/artifact.cjs");
  updateCatalog("NAS_GDP", "National Accounts Statistics — GDP and GVA aggregates", artifactPath, obsCount > 0 ? "ready" : "source_unavailable", obsCount);
  console.log(`  Catalog updated`);

  return artifact;
}

if (require.main === module) {
  try {
    main();
    console.log("[NAS_GDP] DONE");
  } catch (err) {
    console.error(`[NAS_GDP] FAILED: ${err.message}`);
    process.exit(1);
  }
}

module.exports = { main };
